title: Hello, and Thanks for All the Fish
author: breadchris
description: A most excellent adventure in %20
baseurl: /breadchris
url: 'https://breadchris.github.io'
email: chris@vgcs.io
twitter_username: breadchris
github_username: breadchris
markdown: kramdown
permalink: pretty
