title: See you, %20 cowboy
author: breadchris
description: A most excellent adventure in hacking
url: 'https://breadchris.github.io'
email: chris@vgcs.io
twitter_username: breadchris
github_username: breadchris
markdown: kramdown
permalink: pretty
